### ISSUE TITLE
Extension doesnt work when I open VS Code, but does work when I open a different folder

### ISSUE THREAD

**Issue by rababR1** [talhabalaj/vscode-font-changer#10]
I think the two videos below explain the issue.

https://github.com/talhabalaj/vscode-font-changer/assets/65360255/80cf57a4-6f6b-4319-9a1f-74b4cd406e5a

https://github.com/talhabalaj/vscode-font-changer/assets/65360255/b94fdb6d-c8b1-4310-ac6e-1de47511e4f0

**Comment by talhabalaj** [comment]
Most likely in the initial folder you have a workspace configuration in `.vscode` folder and you are setting a font in that config.

**Comment by rababR1** [comment]
Anyway, I fixed it by resetting the font to the default font in Workspace, and it works!
