### ISSUE TITLE
How to make the font selection appear?

### ISSUE THREAD

**Issue by tjthejuggler** [talhabalaj/vscode-font-changer#2]
Cool project! I just cant seem to figure out how to get that font selection menu at the top of the screen.

**Comment by talhabalaj** [comment]
Sorry, I should add it the README soon.

Press "Ctrl + Shift + P" or "Cmd + Shift + P"  and search for "Font
Changer", there should be a command saying "Select Global Font". Select it
will and you will see the fonts menu.

**Comment by tjthejuggler** [comment]
Perfect! Thanks so much! Works like a charm!

**Comment by jrep41** [comment]
Sorry, not change in real time
