### ISSUE TITLE
Add support for other font formats

### ISSUE THREAD

**Issue by iam-amanxz** [talhabalaj/vscode-font-changer#4]
Currently, only the fonts with .ttf and .otf extensions are loaded. Please add support for other formats as well, such as .ttc

**Comment by talhabalaj** [comment]
Got it thanks. I'll add that soon.

**Comment by talhabalaj** [comment]
@iam-amanxz Added support in the new version, Please test it out

**Comment by iam-amanxz** [comment]
> @iam-amanxz Added support in the new version, Please test it out

Doesn't seem to work. Also, the command takes significantly more time than it used to. 
I am using https://github.com/be5invis/Iosevka fonts and they are not loading. I am on a mac btw.

**Comment by talhabalaj** [comment]
Okay, I'll need a mac to test this. Let's see.

**Comment by iam-amanxz** [comment]
> Please test the new version 0.0.7, It's slow but it works. Apparently `.ttc` are big files and take time to parse and load

https://github.com/talhabalaj/vscode-font-changer/assets/50168544/951ffce7-ea82-441d-a89b-5295d7ac6010

It works now, and yes .ttc files are huge it takes time to load. But that's fine I guess. Thank you!

**Comment by talhabalaj** [comment]
You're welcome. I'm going to add a cache for that in the next version hopefully. Closing this issue now

**Comment by talhabalaj** [comment]
Checkout the latest update, #6 has been resolved.
